/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthCard: typeof import('./src/components/auth/AuthCard.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    CreateButton: typeof import('./src/components/buttons/CreateButton.vue')['default']
    CreateProjectModal: typeof import('./src/components/modals/CreateProjectModal.vue')['default']
    CreateTaskModal: typeof import('./src/components/modals/CreateTaskModal.vue')['default']
    Dropdown: typeof import('./src/components/dropdowns/Dropdown.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    OverviewModal: typeof import('./src/components/modals/OverviewModal.vue')['default']
    ProfileDropdown: typeof import('./src/components/dropdowns/ProfileDropdown.vue')['default']
    ProjectDashboard: typeof import('./src/components/projects/projectDashboard.vue')['default']
    ProjectSideNav: typeof import('./src/components/projects/projectSideNav.vue')['default']
    ProjectsModal: typeof import('./src/components/modals/projectsModal.vue')['default']
    Register: typeof import('./src/components/register.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskBoardView: typeof import('./src/components/projects/views/TaskBoardView.vue')['default']
    TaskListView: typeof import('./src/components/projects/views/TaskListView.vue')['default']
    TasksView: typeof import('./src/components/projects/views/TasksView.vue')['default']
  }
}
